services:
  rental_marketplace_db:
    image: postgres:15
    container_name: rental_marketplace_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - rental_marketplace_data:/var/lib/postgresql/data

volumes:
  rental_marketplace_data: